/*
 * shavit's Timer - .inc file
 * by: shavit, rtldg
 *
 * This file is part of shavit's Timer (https://github.com/shavitush/bhoptimer)
 *
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, version 3.0, as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

#if defined _shavit_included
	#endinput
#endif
#define _shavit_included

// compat giga include file

#include <shavit/core>
#include <shavit/chat>
#include <shavit/checkpoints>
#include <shavit/hud>
#include <shavit/mapchooser>
#include <shavit/rankings>
#include <shavit/replay-playback>
#include <shavit/replay-recorder>
#include <shavit/wr>
#include <shavit/zones>

// new plugins (like tas) have been excluded since you should now `#include <shavit/tas>` yourself
